apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-01
  namespace: elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: standard
