apiVersion: v1
kind: Service
metadata:
  name: es-data-01
  namespace: elk
spec:
  selector:
    name: es-data-01
  ports:
    - protocol: TCP
      port: 9203
      targetPort: 9203
      name: api-port
    - protocol: TCP
      port: 9301
      targetPort: 9301
      name: transport-port
