apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elk
spec:
  selector:
    name: es-node-02
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9201
      name: api-port
