apiVersion: v1
kind: Service
metadata:
  name: es-node-02
  namespace: elk
spec:
  selector:
    name: es-node-02
  ports:
    - protocol: TCP
      port: 9201
      targetPort: 9201
      name: api-port
    - protocol: TCP
      port: 9400
      targetPort: 9400
      name: transport-port
