apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-node-04
  namespace: elk
spec:
  selector:
    matchLabels:
      name: es-node-04
  template:
    metadata:
      labels:
        name: es-node-04
    spec:
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: pvc-master-04
      hostname: es-node-04
      setHostnameAsFQDN: true
      containers:
      - image: ashbourne1990/elasticsearch-master-04:es-7.17.11
        name: es-node-04
        livenessProbe:
          tcpSocket:
            port: 9600
          initialDelaySeconds: 240
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /_cat/health
            port: 9204
            httpHeaders:
          initialDelaySeconds: 120
          periodSeconds: 30
        ports:
            - containerPort: 9204
              name: api-port
            - containerPort: 9600
              name: transport-port
        volumeMounts:
            - mountPath: "/var/lib/elasticsearch/data"
              name: data-vol
        resources:
          limits:
            cpu: 1
            memory: 3Gi
          requests:
            cpu: 0.5
            memory: 2Gi
      initContainers:
      - name: init-sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true