apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-master-03
  namespace: elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
