apiVersion: v1
kind: Service
metadata:
  name: es-node-03
  namespace: elk
spec:
  selector:
    name: es-node-03
  ports:
    - protocol: TCP
      port: 9202
      targetPort: 9202
      name: api-port
    - protocol: TCP
      port: 9500
      targetPort: 9500
      name: transport-port
