apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
spec:
  selector:
    name: logstash-fluent
  ports:
    - protocol: TCP
      port: 5044
      targetPort: 5044
      name: http-01
