apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logstash-01
  namespace: elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
